blank_issues_enabled: false
contact_links:
  - name: PointRally Community Discord
    url: https://discord.gg/pointrally
    about: Please ask and answer questions here.
  - name: Security Issues
    url: https://github.com/abeikuforson/pointrally-site/security/policy
    about: Please report security vulnerabilities here.
  - name: Documentation
    url: https://docs.pointrally.com
    about: Check our documentation for guides and API references.